SudokuSolver/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SudokuSolver.Pages
{
    /// <summary>
    /// Logic behind Index.cshtml, generates an empty sudoku field, and handles post requests from Index.cshtml
    /// </summary>
    public class IndexModel : PageModel
    {
        /// <summary>
        /// The sudoku field that is shown to the user, binding the user input for solve
        /// </summary>
        [BindProperty]
        public int?[][] Field { get; set; }

        /// <summary>
        /// Multidimensional array that keeps track of all the positions where a user has filled out the field
        /// </summary>
        public bool[,] UserInputPosition { get; set; }

        /// <summary>
        /// Is false when the field is not valid for solving
        /// </summary>
        public bool FieldIsValid { get; set; }

        /// <summary>
        /// An instance of the solver that will solve the sudoku field
        /// </summary>
        private Solver Solver { get; set; }

        /// <summary>
        /// Constructor, generates an empty sudoku field 
        /// </summary>
        public IndexModel()
        {
            GenerateEmptyField();
            FieldIsValid = true;
        }

        /// <summary>
        /// Post method for handling the clear button, with this a new empty field is generated
        /// </summary>
        public void OnPostClear() {
            //Reset the UI
            ModelState.Clear();
            GenerateEmptyField();
            Error.SetMessage(Error.MESSAGE_TYPE.NO_ERROR);
        }

        /// <summary>
        /// Post method for handling the solve button, uses the solver instance to solve the field
        /// </summary>
        public void OnPostSolve() 
        {
            //Instantiate solver with the current field
            Solver = new Solver(Field);
            //First check if the given board is correct and doesn't break any of the rules
            if (ValidateAndRememberUserInput() && Solver.FieldIsAccordingToSudokuRules())
            {
                //Reset the UI
                Error.SetMessage(Error.MESSAGE_TYPE.NO_ERROR);
                ModelState.Clear();

                //Solve the field and show solution
                Solver.Solve();
                Field = Solver.Field;
            }
            else {
                //Set the valid state to false to show correct UI
                ModelState.Clear();
                FieldIsValid = false;
            }
        }

        /// <summary>
        /// Checks if user input digits are between 1-9 and remembers the position of user input
        /// </summary>
        /// <returns>Returns true if all digits are between 1-9</returns>
        private bool ValidateAndRememberUserInput() 
        {
            for (int i = 0; i < 9; i++)
            {
                for (int j = 0; j < 9; j++)
                {
                    if (Field[i][j] != null) 
                    {
                        UserInputPosition[i, j] = true;
                        if (!(Field[i][j] > 0 && Field[i][j] < 10))
                        {
                            Error.SetMessage(Error.MESSAGE_TYPE.INVALID_DIGIT);
                            return false;
                        }
                    }
                }
            }
            return true;
        }

        /// <summary>
        /// Generates a new empty sudoku field, and resets all the user input indicators to false
        /// </summary>
        public void GenerateEmptyField() 
        {
            Field = new int?[9][];
            //Remember where user input is fo clear visual of result
            UserInputPosition = new bool[9, 9];
            for (int i = 0; i < 9; i++)
            {
                Field[i] = new int?[9];
                for (int j = 0; j < 9; j++)
                {
                    //Set everything to null/false for a fresh start
                    Field[i][j] = null;
                    UserInputPosition[i, j] = false;
                }
            }
        }
    }
}

SudokuSolver/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    ViewData["UnitClass"] = Model.FieldIsValid ? "given" : "given invalid"; 
}
<form class="sudoku" method="post">
    <div class="field" >
        @for (int row = 0; row < 9; row++)
        {
            @for (int col = 0; col < 9; col++)
            {
                if (Model.UserInputPosition[row, col])
                {
                    @Html.TextBoxFor(m => Model.Field[row][col], htmlAttributes: new { Class = ViewData["UnitClass"] });
                }
                else
                {
                    @Html.TextBoxFor(m => Model.Field[row][col]);
                }
            }
        }
    </div>
    <div class="info">
        <div class="rules">
            <h3>Sudoku rules</h3>
            <h6>Only numbers 1-9 are allowed on the field.</h6>
            <h6>You have to fill every row, column and block.</h6>
            <h6>Duplicate values are not allowed in a row, column or block.</h6>
        </div>
        <span class="error">@Error.GetMessage()</span>
        <div>
            <button asp-page-handler="Solve" class="main" type="submit">Solve field</button>
            <button asp-page-handler="Clear" class=accent type="submit">Clear field</button>
        </div>
    </div>
</form>

SudokuSolver/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sudoku Solver</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="icon" href="~/favicon.png" />
</head>
<body>
    <header>
        <nav>
            <h2>Sudoku solver</h2>
        </nav>
    </header>
    <div class="sudoku">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>